{"level":"info","memory_mb":14.193367004394531,"message":"Phase started: Edge Processing","phase":"Edge Processing","timestamp":117}
{"context":{"limit":5000,"offset":0},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:91:20)\n    at async Promise.all (index 0)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:57:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":5135}
{"context":{"limit":5000,"offset":100000},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:91:20)\n    at async Promise.all (index 20)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:57:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":5136}
{"context":{"limit":5000,"offset":105000},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:91:20)\n    at async Promise.all (index 21)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:57:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":5138}
{"context":{"limit":5000,"offset":110000},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:91:20)\n    at async Promise.all (index 22)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:57:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":5138}
{"context":{"limit":5000,"offset":115000},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:91:20)\n    at async Promise.all (index 23)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:57:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":5139}
{"context":{"limit":5000,"offset":120000},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:91:20)\n    at async Promise.all (index 24)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:57:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":5140}
{"context":{"limit":5000,"offset":125000},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:91:20)\n    at async Promise.all (index 25)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:57:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":5141}
{"context":{"limit":5000,"offset":130000},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:91:20)\n    at async Promise.all (index 26)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:57:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":5142}
{"context":{"limit":5000,"offset":135000},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:91:20)\n    at async Promise.all (index 27)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:57:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":5143}
{"context":{"limit":5000,"offset":140000},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:91:20)\n    at async Promise.all (index 28)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:57:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":5145}
{"context":{"limit":5000,"offset":20000},"level":"error","message":"Error occurred","stack":"AggregateError\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:524:28)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:91:20)\n    at async Promise.all (index 4)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:57:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":5469}
{"context":{"limit":5000,"offset":335000},"level":"error","message":"Error occurred socket hang up","stack":"Error: socket hang up\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketOnEnd (node:_http_client:542:5)\n    at TLSSocket.emit (node:events:536:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:91:20)\n    at async Promise.all (index 67)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:57:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":20114}
{"context":{"limit":5000,"offset":175000},"level":"error","message":"Error occurred socket hang up","stack":"Error: socket hang up\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketOnEnd (node:_http_client:542:5)\n    at TLSSocket.emit (node:events:536:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:91:20)\n    at async Promise.all (index 35)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:57:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":20481}
{"context":{"limit":5000,"offset":340000},"level":"error","message":"Error occurred socket hang up","stack":"Error: socket hang up\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketOnEnd (node:_http_client:542:5)\n    at TLSSocket.emit (node:events:536:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:91:20)\n    at async Promise.all (index 68)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:57:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":27031}
{"context":{"limit":5000,"offset":250000},"level":"error","message":"Error occurred socket hang up","stack":"Error: socket hang up\n    at Function.AxiosError.from (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\AxiosError.js:92:14)\n    at RedirectableRequest.handleRequestError (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\adapters\\http.js:620:25)\n    at RedirectableRequest.emit (node:events:536:35)\n    at eventHandlers.<computed> (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\follow-redirects@1.15.11\\node_modules\\follow-redirects\\index.js:49:24)\n    at ClientRequest.emit (node:events:524:28)\n    at emitErrorEvent (node:_http_client:104:11)\n    at TLSSocket.socketOnEnd (node:_http_client:542:5)\n    at TLSSocket.emit (node:events:536:35)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)\n    at Axios.request (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\node_modules\\.pnpm\\axios@1.11.0\\node_modules\\axios\\lib\\core\\Axios.js:45:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async Case4aEdge.processEdgeBatch (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:91:20)\n    at async Promise.all (index 50)\n    at async Case4aEdge.execute (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\cases\\case4a-edge.ts:57:25)\n    at async main (C:\\Users\\arnav\\OneDrive\\Desktop\\PROGRAMMING\\project web development\\ETL\\elt-khund-pipeline-benchmark\\src\\index.ts:54:23)","timestamp":27986}
